name: Deploy Diagram to Camunda SaaS

on:
  pull_request:
  push:
    paths:
      - '**/*.bpmn'
  
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up zbctl
        run: |
          sudo apt-get update
          npm install -g zbctl

      - name: Check zbctl status
        env:
          ZEEBE_ADDRESS: '063f6ba6-d712-4b42-aab9-2a62e45efa61.bru-2.zeebe.camunda.io:443'
          ZEEBE_CLIENT_ID: 'HOVhVO73vS11c9IY4Lto7XO-qbG7P9Z0'
          ZEEBE_CLIENT_SECRET: 'TMFkae9H~ZHs7hR90QUFFWlxG7bG9ImEys-UJw7rqz166dVdoHERNHBzH7qrk_tG'
          ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.camunda.io/oauth/token'
        run: |
          zbctl status
            
            
      - name: Deploy BPMN to Zeebe
        env:
          ZEEBE_ADDRESS: '063f6ba6-d712-4b42-aab9-2a62e45efa61.bru-2.zeebe.camunda.io:443'
          ZEEBE_CLIENT_ID: 'HOVhVO73vS11c9IY4Lto7XO-qbG7P9Z0'
          ZEEBE_CLIENT_SECRET: 'TMFkae9H~ZHs7hR90QUFFWlxG7bG9ImEys-UJw7rqz166dVdoHERNHBzH7qrk_tG'
          ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.camunda.io/oauth/token'
        run: |
          zbctl deploy '../Webinar-8.6/src/main/resources/bank loan origination and processing.bpmn'

