name: Deploy Diagram to Camunda SaaS

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**/*.bpmn'
  
  workflow_dispatch:

jobs:
  deploy-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up zbctl
        run: |
          sudo apt-get update
          npm install -g zbctl

      - name: Deploy BPMN to Zeebe
        env:
          ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
          ZEEBE_CLIENT_ID: ${{ secrets.ZEEBE_CLIENT_ID }}
          ZEEBE_CLIENT_SECRET: ${{ secrets.ZEEBE_CLIENT_SECRET }}
          ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.camunda.io/oauth/token'
        run: |
          zbctl status
          zbctl deploy src/main/resources/webinar8.6.bpmn

